# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50a75ddb79d85d32bee5e8fcf146f396086cfc156d658367e8434b1d1ba7f1bc1d87c7a0b400563a4b0c949b265e52ea160476c10a20ed63d5dd77903b6e0299

test:
  secret_key_base: 7717057d53305c2a094fbc70fb1850c461f99b3cffaaaff9a2c625158e8d6d233e48ea8520437a9a33e47e60dc9e7e0daec8b0862e2c91f741207b50b45fbd6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
