# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0759455892c15d48db8be60bf1f226ae32ae39fa28435f1b29e49bc9144cca9a254e264742391647061ba9f4eb6b046baeab34d21e0e9a31e4ffefd770a8044f

test:
  secret_key_base: 42c1c45a63c24c9f9149a413e29e016e94f44770c803747f745d9c6bb75f440e755566f796de1f8a6f13dba0e7fad2dc97e91f7b6e48b135430f0c42bb0cfcaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
