# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54ad256d062828078d2985f3d7f5651bfab7470c57f9b843d3b14d1377e72137423b386e156eb5180c203aff78eb0df98ab4f69ec9905a03a64c03cf7685e4d9

test:
  secret_key_base: 8ff5c7a1357712f34f1fd241eb419a989bf87a88c8ad85a5c334d8d6dbf18d66f866adf1091fe8d3834cb2c03f273391540fb6a1e03d52ac5fc9da7d1c62ecec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
