# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 835c171ef7808af177327c20f6198cf9b5aa20f71f5b817e86586ca7c9c2aae4c8d0ecbcb3b09dbae13f15b66af3a0cadb9626f57d5d08944bfbbb3b3f67b47d

test:
  secret_key_base: c548beedcf314021fd7bbc79016d973a3f7d2ea784c2681b621727ea10a28fd06cb17aca478a9a02b494c3ce5df546b3c56dfb4b3a8a297b05b678f3065da508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
